inherit_from: .rubocop-default.yml

AllCops:
  DisplayStyleGuide: true
  ExtraDetails: true

Metrics/LineLength:
  # Description: 'Limit lines to 100 characters.'
  # StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#80-character-limits'
  Max: 100

Style/SymbolArray:
  Enabled: false