require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  Exclude:
    - db/migrate/*
  TargetRubyVersion: ~

Layout/LineLength:
  Max: 110

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  CountComments: true  # count full line comments?
  Max: 25
  ExcludedMethods: []
  Exclude:
    - "spec/**/*"
    - "lib/tasks/*"
    - "Guardfile"
    - "Gemfile"
    - app/models/chart/globals.rb
    - app/models/chart/sensor_values.rb

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: true